local_repository(
    name = "rules_oci",
    path = "../../../",
)

load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")

rules_oci_dependencies()

load("@rules_oci//oci:repositories.bzl", "oci_register_toolchains")

oci_register_toolchains(name = "oci")

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "empty_image",
    digest = "sha256:fa6f1b1fe754805b7faf3f4ffaad3da4b492a703886c8157acf2a2504d8ad3e4",
    image = "http://localhost:1447/empty_image",
)
